export const alarmConstants = {
	GET_ALARM_CHECK: 'GET_ALARM_CHECK',
	GET_ALARM_CHECK_SUCCESS: 'GET_ALARM_CHECK_SUCCESS',
	GET_ALARM_CHECK_ERROR: 'GET_ALARM_CHECK_ERROR',
	PUT_ALARM_SELECTED: 'PUT_ALARM_SELECTED',
	PUT_ALARM_SELECTED_SUCCESS: 'PUT_ALARM_SELECTED_SUCCESS',
	PUT_ALARM_SELECTED_ERROR: 'PUT_ALARM_SELECTED_ERROR',
}
