export const boardConstants = {
	GET_BOARD_PAGE_LIST: 'GET_BOARD_PAGE_LIST',
	GET_BOARD_PAGE_LIST_SUCCESS: 'GET_BOARD_PAGE_LIST_SUCCESS',
	GET_BOARD_PAGE_LIST_ERROR: 'GET_BOARD_PAGE_LIST_ERROR',
	GET_BOARD_NORMAL_LIST: 'GET_BOARD_NORMAL_LIST',
	GET_BOARD_NORMAL_LIST_SUCCESS: 'GET_BOARD_NORMAL_LIST_SUCCESS',
	GET_BOARD_NORMAL_LIST_ERROR: 'GET_BOARD_NORMAL_LIST_ERROR',
	GET_BOARD_DETAIL: 'GET_BOARD_DETAIL',
	GET_BOARD_DETAIL_SUCCESS: 'GET_BOARD_DETAIL_SUCCESS',
	GET_BOARD_DETAIL_ERROR: 'GET_BOARD_DETAIL_ERROR',
	POST_INQUIRY_INSERT: 'POST_INQUIRY_INSERT',
	POST_INQUIRY_INSERT_SUCCESS: 'POST_INQUIRY_INSERT_SUCCESS',
	POST_INQUIRY_INSERT_ERROR: 'POST_INQUIRY_INSERT_ERROR',
}
