export const boxOfficeConstants = {
	GET_BOX_OFFICE_LIST: 'GET_BOX_OFFICE_LIST',
	GET_BOX_OFFICE_LIST_SUCCESS: 'GET_BOX_OFFICE_LIST_SUCCESS',
	GET_BOX_OFFICE_LIST_ERROR: 'GET_BOX_OFFICE_LIST_ERROR',
	GET_BOX_OFFICE_DETAIL: 'GET_BOX_OFFICE_DETAIL',
	GET_BOX_OFFICE_DETAIL_SUCCESS: 'GET_BOX_OFFICE_DETAIL_SUCCESS',
	GET_BOX_OFFICE_DETAIL_ERROR: 'GET_BOX_OFFICE_DETAIL_ERROR',
	GET_BOX_OFFICE_PEOPLE: 'GET_BOX_OFFICE_PEOPLE',
	GET_BOX_OFFICE_PEOPLE_SUCCESS: 'GET_BOX_OFFICE_PEOPLE_SUCCESS',
	GET_BOX_OFFICE_PEOPLE_ERROR: 'GET_BOX_OFFICE_PEOPLE_ERROR',
}
