export const commCodeConstants = {
	GET_COMM_CODE_SEARCH_LIST: 'GET_COMM_CODE_SEARCH_LIST',
	GET_COMM_CODE_SEARCH_LIST_SUCCESS: 'GET_COMM_CODE_SEARCH_LIST_SUCCESS',
	GET_COMM_CODE_SEARCH_LIST_ERROR: 'GET_COMM_CODE_SEARCH_LIST_ERROR',
}
