export const connectorConstants = {
	GET_CONNECTOR_STATUS: 'GET_CONNECTOR_STATUS',
	GET_CONNECTOR_STATUS_SUCCESS: 'GET_CONNECTOR_STATUS_SUCCESS',
	GET_CONNECTOR_STATUS_ERROR: 'GET_CONNECTOR_STATUS_ERROR',
	GET_STATUS_AVAILABLE: 'GET_STATUS_AVAILABLE',
	GET_STATUS_AVAILABLE_SUCCESS: 'GET_STATUS_AVAILABLE_SUCCESS',
	GET_STATUS_AVAILABLE_ERROR: 'GET_STATUS_AVAILABLE_ERROR',
}
