export const evConstants = {
	GET_EV_MANUFACTURER_LIST: 'GET_EV_MANUFACTURER_LIST',
	GET_EV_MANUFACTURER_LIST_SUCCESS: 'GET_EV_MANUFACTURER_LIST_SUCCESS',
	GET_EV_MANUFACTURER_LIST_ERROR: 'GET_EV_MANUFACTURER_LIST_ERROR',

	GET_EV_MODEL_LIST: 'GET_EV_MODEL_LIST',
	GET_EV_MODEL_LIST_SUCCESS: 'GET_EV_MODEL_LIST_SUCCESS',
	GET_EV_MODEL_LIST_ERROR: 'GET_EV_MODEL_LIST_ERROR',
}
