export const inicisConstants = {
	GET_WPAY_MEM_REQUEST: 'GET_WPAY_MEM_REQUEST',
	GET_WPAY_MEM_REQUEST_SUCCESS: 'GET_WPAY_MEM_REQUEST_SUCCESS',
	GET_WPAY_MEM_REQUEST_ERROR: 'GET_WPAY_MEM_REQUEST_ERROR',

	GET_WPAY_CARD_REQUEST: 'GET_WPAY_CARD_REQUEST',
	GET_WPAY_CARD_REQUEST_SUCCESS: 'GET_WPAY_CARD_REQUEST_SUCCESS',
	GET_WPAY_CARD_REQUEST_ERROR: 'GET_WPAY_CARD_REQUEST_ERROR',

	GET_WPAY_CARD_LIST: 'GET_WPAY_CARD_LIST',
	GET_WPAY_CARD_LIST_SUCCESS: 'GET_WPAY_CARD_LIST_SUCCESS',
	GET_WPAY_CARD_LIST_ERROR: 'GET_WPAY_CARD_LIST_ERROR',

	GET_WPAY_AUTH_REQUEST: 'GET_WPAY_AUTH_REQUEST',
	GET_WPAY_AUTH_REQUEST_SUCCESS: 'GET_WPAY_AUTH_REQUEST_SUCCESS',
	GET_WPAY_AUTH_REQUEST_ERROR: 'GET_WPAY_AUTH_REQUEST_ERROR',

	POST_WPAY_CARD_REMOVE: 'POST_WPAY_CARD_REMOVE',
	POST_WPAY_CARD_REMOVE_SUCCESS: 'POST_WPAY_CARD_REMOVE_SUCCESS',
	POST_WPAY_CARD_REMOVE_ERROR: 'POST_WPAY_CARD_REMOVE_ERROR',

	POST_WPAY_CARD_MAIN: 'POST_WPAY_CARD_MAIN',
	POST_WPAY_CARD_MAIN_SUCCESS: 'POST_WPAY_CARD_MAIN_SUCCESS',
	POST_WPAY_CARD_MAIN_ERROR: 'POST_WPAY_CARD_MAIN_ERROR',
}
