export const messageConstants = {
	GET_MESSAGE_LIST: 'GET_MESSAGE_LIST',
	GET_MESSAGE_LIST_SUCCESS: 'GET_MESSAGE_LIST_SUCCESS',
	GET_MESSAGE_LIST_ERROR: 'GET_MESSAGE_LIST_ERROR',
	PATCH_READ_VALUE: 'PATCH_READ_VALUE',
	PATCH_READ_VALUE_SUCCESS: 'PATCH_READ_VALUE_SUCCESS',
	PATCH_READ_VALUE_ERROR: 'PATCH_READ_VALUE_ERROR',
	GET_UNREAD_COUNT: 'GET_UNREAD_COUNT',
	GET_UNREAD_COUNT_SUCCESS: 'GET_UNREAD_COUNT_SUCCESS',
	GET_UNREAD_COUNT_ERROR: 'GET_UNREAD_COUNT_ERROR',
	GET_MESSAGE_DETAIL: 'GET_MESSAGE_DETAIL',
	GET_MESSAGE_DETAIL_SUCCESS: 'GET_MESSAGE_DETAIL_SUCCESS',
	GET_MESSAGE_DETAIL_ERROR: 'GET_MESSAGE_DETAIL_ERROR',
}
