export const paymentConstants = {
	GET_RECENT_CHARGE_LIST: 'GET_RECENT_CHARGE_LIST',
	GET_RECENT_CHARGE_LIST_SUCCESS: 'GET_RECENT_CHARGE_LIST_SUCCESS',
	GET_RECENT_CHARGE_LIST_ERROR: 'GET_RECENT_CHARGE_LIST_ERROR',

	GET_PAYMENT_DETAIL: 'GET_PAYMENT_DETAIL',
	GET_PAYMENT_DETAIL_SUCCESS: 'GET_PAYMENT_DETAIL_SUCCESS',
	GET_PAYMENT_DETAIL_ERROR: 'GET_PAYMENT_DETAIL_ERROR',

	GET_PAYMENT_LIST: 'GET_PAYMENT_LIST',
	GET_PAYMENT_LIST_SUCCESS: 'GET_PAYMENT_LIST_SUCCESS',
	GET_PAYMENT_LIST_ERROR: 'GET_PAYMENT_LIST_ERROR',

	GET_IS_UNPAID: 'GET_IS_UNPAID',
	GET_IS_UNPAID_SUCCESS: 'GET_IS_UNPAID_SUCCESS',
	GET_IS_UNPAID_ERROR: 'GET_IS_UNPAID_ERROR',
}
