export const promotionConstants = {
	GET_PROMOTION_LIST_PAGE: 'GET_PROMOTION_LIST_PAGE',
	GET_PROMOTION_LIST_PAGE_SUCCESS: 'GET_PROMOTION_LIST_PAGE_SUCCESS',
	GET_PROMOTION_LIST_PAGE_ERROR: 'GET_PROMOTION_LIST_PAGE_ERROR',
}
