export const stationConstants = {
	GET_STATION_LIST: 'GET_STATION_LIST',
	GET_STATION_LIST_SUCCESS: 'GET_STATION_LIST_SUCCESS',
	GET_STATION_LIST_ERROR: 'GET_STATION_LIST_ERROR',

	GET_STATION_DETAIL: 'GET_STATION_DETAIL',
	GET_STATION_DETAIL_SUCCESS: 'GET_STATION_DETAIL_SUCCESS',
	GET_STATION_DETAIL_ERROR: 'GET_STATION_DETAIL_ERROR',

	GET_STATION_WAITING: 'GET_STATION_WAITING',
	GET_STATION_WAITING_SUCCESS: 'GET_STATION_WAITING_SUCCESS',
	GET_STATION_WAITING_ERROR: 'GET_STATION_WAITING_ERROR',

	POST_STATION_CHARGE: 'POST_STATION_CHARGE',
	POST_STATION_CHARGE_SUCCESS: 'POST_STATION_CHARGE_SUCCESS',
	POST_STATION_CHARGE_ERROR: 'POST_STATION_CHARGE_ERROR',

	GET_NEAR_STATION_PAGING_LIST: 'GET_NEAR_STATION_PAGING_LIST',
	GET_NEAR_STATION_PAGING_LIST_SUCCESS: 'GET_NEAR_STATION_PAGING_LIST_SUCCESS',
	GET_NEAR_STATION_PAGING_LIST_ERROR: 'GET_NEAR_STATION_PAGING_LIST_ERROR',

	GET_FIND_ROAD: 'GET_FIND_ROAD',
	GET_FIND_ROAD_SUCCESS: 'GET_FIND_ROAD_SUCCESS',
	GET_FIND_ROAD_ERROR: 'GET_FIND_ROAD_ERROR',

	GET_FIND_ROAD_REQ_DATA: 'GET_FIND_ROAD_REQ_DATA',
	GET_FIND_ROAD_REQ_DATA_SUCCESS: 'GET_FIND_ROAD_REQ_DATA_SUCCESS',
	GET_FIND_ROAD_REQ_DATA_ERROR: 'GET_FIND_ROAD_REQ_DATA_ERROR',

	GET_USER_STATION_LIST: 'GET_USER_STATION_LIST',
	GET_USER_STATION_LIST_SUCCESS: 'GET_USER_STATION_LIST_SUCCESS',
	GET_USER_STATION_LIST_ERROR: 'GET_USER_STATION_LIST_ERROR',
}
