export const termsConstants = {
	GET_TERMS_LIST: 'GET_TERMS_LIST',
	GET_TERMS_LIST_SUCCESS: 'GET_TERMS_LIST_SUCCESS',
	GET_TERMS_LIST_ERROR: 'GET_TERMS_LIST_ERROR',

	GET_PERSONAL_TERMS_LIST: 'GET_PERSONAL_TERMS_LIST',
	GET_PERSONAL_TERMS_LIST_SUCCESS: 'GET_PERSONAL_TERMS_LIST_SUCCESS',
	GET_PERSONAL_TERMS_LIST_ERROR: 'GET_PERSONAL_TERMS_LIST_ERROR',

	GET_CORP_TERMS_LIST: 'GET_CORP_TERMS_LIST',
	GET_CORP_TERMS_LIST_SUCCESS: 'GET_CORP_TERMS_LIST_SUCCESS',
	GET_CORP_TERMS_LIST_ERROR: 'GET_CORP_TERMS_LIST_ERROR',
}
