export const userFavoriteStationConstants = {
	GET_FAVORITE_STATION_NORMAL_LIST: 'GET_FAVORITE_STATION_NORMAL_LIST',
	GET_FAVORITE_STATION_NORMAL_LIST_SUCCESS: 'GET_FAVORITE_STATION_NORMAL_LIST_SUCCESS',
	GET_FAVORITE_STATION_NORMAL_LIST_ERROR: 'GET_FAVORITE_STATION_NORMAL_LIST_ERROR',
	GET_FAVORITE_STATION_PAGING_LIST: 'GET_FAVORITE_STATION_PAGING_LIST',
	GET_FAVORITE_STATION_PAGING_LIST_SUCCESS: 'GET_FAVORITE_STATION_PAGING_LIST_SUCCESS',
	GET_FAVORITE_STATION_PAGING_LIST_ERROR: 'GET_FAVORITE_STATION_PAGING_LIST_ERROR',
	GET_FAVORITE_STATION_LIST: 'GET_FAVORITE_STATION_LIST',
	GET_FAVORITE_STATION_LIST_SUCCESS: 'GET_FAVORITE_STATION_LIST_SUCCESS',
	GET_FAVORITE_STATION_LIST_ERROR: 'GET_FAVORITE_STATION_LIST_ERROR',
	GET_FAVORITE_STATION: 'GET_FAVORITE_STATION',
	GET_FAVORITE_STATION_SUCCESS: 'GET_FAVORITE_STATION_SUCCESS',
	GET_FAVORITE_STATION_ERROR: 'GET_FAVORITE_STATION_ERROR',

	POST_BOOK_MARK_INSERT: 'POST_BOOK_MARK_INSERT',
	POST_BOOK_MARK_INSERT_SUCCESS: 'POST_BOOK_MARK_INSERT_SUCCESS',
	POST_BOOK_MARK_INSERT_ERROR: 'POST_BOOK_MARK_INSERT_ERROR',

	DELETE_FAVORITE_STATION: 'DELETE_FAVORITE_STATION',
	DELETE_FAVORITE_STATION_SUCCESS: 'DELETE_FAVORITE_STATION_SUCCESS',
	DELETE_FAVORITE_STATION_ERROR: 'DELETE_FAVORITE_STATION_ERROR',

	UPDATE_FAVORITE_STATION: 'UPDATE_FAVORITE_STATION',
	UPDATE_FAVORITE_STATION_SUCCESS: 'UPDATE_FAVORITE_STATION_SUCCESS',
	UPDATE_FAVORITE_STATION_ERROR: 'UPDATE_FAVORITE_STATION_ERROR',

	POST_TOGGLE_BOOK_MARK: 'POST_TOGGLE_BOOK_MARK',
	POST_TOGGLE_BOOK_MARK_SUCCESS: 'POST_TOGGLE_BOOK_MARK_SUCCESS',
	POST_TOGGLE_BOOK_MARK_ERROR: 'POST_TOGGLE_BOOK_MARK_ERROR',
}
