export const userEvConstants = {
	GET_USER_EV_LIST: 'GET_USER_EV_LIST',
	GET_USER_EV_LIST_SUCCESS: 'GET_USER_EV_LIST_SUCCESS',
	GET_USER_EV_LIST_ERROR: 'GET_USER_EV_LIST_ERROR',

	GET_MY_EV_LIST: 'GET_MY_EV_LIST',
	GET_MY_EV_LIST_SUCCESS: 'GET_MY_EV_LIST_SUCCESS',
	GET_MY_EV_LIST_ERROR: 'GET_MY_EV_LIST_ERROR',

	GET_SHARED_EV_LIST: 'GET_SHARED_EV_LIST',
	GET_SHARED_EV_LIST_SUCCESS: 'GET_SHARED_EV_LIST_SUCCESS',
	GET_SHARED_EV_LIST_ERROR: 'GET_SHARED_EV_LIST_ERROR',

	GET_SHARED_USER_EV_LIST: 'GET_SHARED_USER_EV_LIST',
	GET_SHARED_USER_EV_LIST_SUCCESS: 'GET_SHARED_USER_EV_LIST_SUCCESS',
	GET_SHARED_USER_EV_LIST_ERROR: 'GET_SHARED_USER_EV_LIST_ERROR',

	GET_USER_MY_EV_LIST: 'GET_USER_MY_EV_LIST',
	GET_USER_MY_EV_LIST_SUCCESS: 'GET_USER_MY_EV_LIST_SUCCESS',
	GET_USER_MY_EV_LIST_ERROR: 'GET_USER_MY_EV_LIST_ERROR',

	GET_SHARED_USER_LIST: 'GET_SHARED_USER_LIST',
	GET_SHARED_USER_LIST_SUCCESS: 'GET_SHARED_USER_LIST_SUCCESS',
	GET_SHARED_USER_LIST_ERROR: 'GET_SHARED_USER_LIST_ERROR',

	GET_RECEIVED_SHARE_LIST: 'GET_RECEIVED_SHARE_LIST',
	GET_RECEIVED_SHARE_LIST_SUCCESS: 'GET_RECEIVED_SHARE_LIST_SUCCESS',
	GET_RECEIVED_SHARE_LIST_ERROR: 'GET_RECEIVED_SHARE_LIST_ERROR',

	GET_NEW_USER_EV_LIST: 'GET_NEW_USER_EV_LIST',
	GET_NEW_USER_EV_LIST_SUCCESS: 'GET_NEW_USER_EV_LIST_SUCCESS',
	GET_NEW_USER_EV_LIST_ERROR: 'GET_NEW_USER_EV_LIST_ERROR',

	GET_USER_EV_INFO: 'GET_USER_EV_INFO',
	GET_USER_EV_INFO_SUCCESS: 'GET_USER_EV_INFO_SUCCESS',
	GET_USER_EV_INFO_ERROR: 'GET_USER_EV_INFO_ERROR',

	POST_SEND_SHARE: 'POST_SEND_SHARE',
	POST_SEND_SHARE_SUCCESS: 'POST_SEND_SHARE_SUCCESS',
	POST_SEND_SHARE_ERROR: 'POST_SEND_SHARE_ERROR',

	PATCH_REFUSE_SHARE: 'PATCH_REFUSE_SHARE',
	PATCH_REFUSE_SHARE_SUCCESS: 'PATCH_REFUSE_SHARE_SUCCESS',
	PATCH_REFUSE_SHARE_ERROR: 'PATCH_REFUSE_SHARE_ERROR',

	GET_CHECK_SHARE: 'GET_CHECK_SHARE',
	GET_CHECK_SHARE_SUCCESS: 'GET_CHECK_SHARE_SUCCESS',
	GET_CHECK_SHARE_ERROR: 'GET_CHECK_SHARE_ERROR',

	POST_APPROVE_SHARE: 'POST_APPROVE_SHARE',
	POST_APPROVE_SHARE_SUCCESS: 'POST_APPROVE_SHARE_SUCCESS',
	POST_APPROVE_SHARE_ERROR: 'POST_APPROVE_SHARE_ERROR',

	POST_ADD_EV: 'POST_ADD_EV',
	POST_ADD_EV_SUCCESS: 'POST_ADD_EV_SUCCESS',
	POST_ADD_EV_ERROR: 'POST_ADD_EV_ERROR',

	PATCH_USER_EV: 'PATCH_USER_EV',
	PATCH_USER_EV_SUCCESS: 'PATCH_USER_EV_SUCCESS',
	PATCH_USER_EV_ERROR: 'PATCH_USER_EV_ERROR',

	PATCH_STOP_SHARE: 'PATCH_STOP_SHARE',
	PATCH_STOP_SHARE_SUCCESS: 'PATCH_STOP_SHARE_SUCCESS',
	PATCH_STOP_SHARE_ERROR: 'PATCH_STOP_SHARE_ERROR',

	PATCH_RELEASE_SHARE: 'PATCH_RELEASE_SHARE',
	PATCH_RELEASE_SHARE_SUCCESS: 'PATCH_RELEASE_SHARE_SUCCESS',
	PATCH_RELEASE_SHARE_ERROR: 'PATCH_RELEASE_SHARE_ERROR',

	DELETE_USER_EV: 'DELETE_USER_EV',
	DELETE_USER_EV_SUCCESS: 'DELETE_USER_EV_SUCCESS',
	DELETE_USER_EV_ERROR: 'DELETE_USER_EV_ERROR',
}
